disabled_rules:
  - identifier_name
  - function_body_length
  - orphaned_doc_comment
  - cyclomatic_complexity
  - force_cast
  - file_length
  - type_body_length

included:
  - JobTrack

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
